version: "3.8"

volumes:
  pg:
    driver: local

services:
  postgres:
    image: postgres:15.3-alpine
    volumes:
      - pg:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
